services:
  redis:
    image: redis:7
    container_name: atfeelog-redis
    restart: unless-stopped
    mem_limit: 100m
    ports:
      - "6379:6379"

  app:
    image: nadaa97/atfeelog-backend:latest
    container_name: atfeelog-app
    restart: unless-stopped
    mem_limit: 700m
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx450m -XX:MaxMetaspaceSize=150m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.pcsbfbstuewcnzufsxod
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${AWS_SECRET_KEY}
      CLOUD_AWS_REGION_STATIC: ap-northeast-2
      CLOUD_AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: "true"
      SPRING_GRAPHQL_PATH: /graphql
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
    depends_on:
      redis:
        condition: service_started
