services:
  redis:
    image: redis:7
    container_name: atfeelog-redis
    ports:
      - "6379:6379"

  app:
    image: nadaa97/atfeelog-backend:latest
    container_name: atfeelog-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.pcsbfbstuewcnzufsxod.supabase.co:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_started
